openapi: 3.0.0
info:
  title: REST_API
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:5000'
paths:
  /admin:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-admin
  '/<string:name>':
    post:
      summary: ''
      operationId: 'post-string:name'
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: string
          in: query
          name: /
    parameters: []
components:
  schemas: {}
